# Generated by Django 5.1.3 on 2024-12-03 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('especificacoes', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='tecnoApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('Orçamento', 'Orçamento'), ('Proposta de Contrato', 'Proposta de Contrato'), ('Outros', 'Outros')], max_length=50)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('Manutenção Hidráulica Taxa Zero', 'Manutenção Hidráulica Taxa Zero'), ('Manutenção Hidráulica Comum', 'Manutenção Hidráulica Comum'), ('Tratamento Químico da Piscina', 'Tratamento Químico da Piscina')], max_length=50, null=True)),
                ('servico', models.TextField(blank=True, help_text="Detalhes do orçamento (apenas para tipo 'Orçamento').", null=True)),
                ('especificacoes', models.TextField(blank=True, help_text="Informações adicionais (apenas para tipo 'Outros').", null=True)),
                ('incluir_todos_equipamentos', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='tecnoApp.usuario')),
                ('equipamentos', models.ManyToManyField(related_name='documentos', to='tecnoApp.equipamentos')),
            ],
        ),
    ]
