# Generated by Django 5.1.3 on 2024-12-04 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoApp', '0004_alter_usuario_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='tecnoApp.usuario'),
        ),
    ]
